// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models;

public partial class Comment
{
    public string CommentId { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string NewsArticleId { get; set; }

    public int? AccountId { get; set; }

    public bool? IsDelete { get; set; }

    public virtual SystemAccount Account { get; set; }

    public virtual NewsArticle NewsArticle { get; set; }
}