// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models;

public partial class SystemAccount
{
    public int AccountId { get; set; }

    public string AccountName { get; set; }

    public string AccountEmail { get; set; }

    public int? AccountRole { get; set; }

    public string AccountPassword { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<NewsArticle> NewsArticles { get; set; } = new List<NewsArticle>();
}